/**
 * Atlas-native sprite core.
 *
 * Sprites are generated by AutoSprite: one sheet PER character PER animation
 * state (idle/walk/action/happy), each a uniform grid of square frames laid
 * left->right, top->bottom. The per-sheet geometry (frame size, frame count,
 * columns) is baked into `sprite-manifest.ts` straight from AutoSprite's atlas
 * metadata — there are no hand-tuned bounding boxes. Regenerating art means
 * re-running the fetch step; no code edits.
 *
 * Backgrounds are keyed to true alpha offline, so frames draw directly.
 */
export type SpriteState = "idle" | "walk" | "action" | "happy";

/** One animation strip: a file plus its uniform-grid geometry. */
export interface AnimMeta {
  file: string; // path under /sprites, e.g. "animals/cow/walk.webp"
  fw: number; // frame width (px)
  fh: number; // frame height (px)
  count: number; // number of frames
  cols: number; // columns in the grid
  // Tight content box within a cell (union over all frames), so the figure
  // fills the draw box instead of floating in AutoSprite's transparent padding.
  trim: { x: number; y: number; w: number; h: number };
}

export type CharAnims = Record<SpriteState, AnimMeta>;

const FPS: Record<SpriteState, number> = {
  idle: 7,
  walk: 15,
  action: 11,
  happy: 16,
};

interface Loaded {
  img: HTMLImageElement;
  meta: AnimMeta;
  ok: boolean;
}

/**
 * Loads and animates the set of state-sheets for a single character. Sheets
 * load lazily on first reference; `ready()` is true once idle has decoded
 * (enough to start drawing — other states stream in behind it).
 */
export class SpriteSet {
  private slots: Partial<Record<SpriteState, Loaded>> = {};

  constructor(private anims: CharAnims) {
    this.load("idle");
  }

  private load(state: SpriteState): Loaded | undefined {
    const existing = this.slots[state];
    if (existing) return existing;
    const meta = this.anims[state];
    if (!meta) return undefined;
    const img = new Image();
    const slot: Loaded = { img, meta, ok: false };
    img.onload = () => {
      slot.ok = img.width > 0;
    };
    img.onerror = () => {
      slot.ok = false;
    };
    img.src = `/sprites/${meta.file}`;
    this.slots[state] = slot;
    return slot;
  }

  ready(): boolean {
    return !!this.slots.idle?.ok;
  }

  /** Resolve the state to draw, falling back to idle until its sheet decodes. */
  private resolve(state: SpriteState): Loaded | undefined {
    const slot = this.load(state);
    if (slot?.ok) return slot;
    const idle = this.slots.idle;
    return idle?.ok ? idle : undefined;
  }

  private frameIndex(meta: AnimMeta, state: SpriteState, timeMs: number, phase: number): number {
    const n = meta.count;
    const i = Math.floor((timeMs / 1000) * FPS[state] + phase * n);
    return ((i % n) + n) % n;
  }

  /** Source rect of frame `i`, cropped to the content box. */
  private srcRect(meta: AnimMeta, i: number): [number, number, number, number] {
    const cx = (i % meta.cols) * meta.fw;
    const cy = Math.floor(i / meta.cols) * meta.fh;
    const t = meta.trim;
    return [cx + t.x, cy + t.y, t.w, t.h];
  }

  /** Draw centred (preserving aspect) in a `size` x `size` box at (cx,cy). */
  drawCentred(
    ctx: CanvasRenderingContext2D,
    state: SpriteState,
    timeMs: number,
    phase: number,
    cx: number,
    cy: number,
    size: number,
  ): void {
    const slot = this.resolve(state);
    if (!slot) return;
    const { img, meta } = slot;
    const drawState = slot === this.slots[state] ? state : "idle";
    const [sx, sy, sw, sh] = this.srcRect(meta, this.frameIndex(meta, drawState, timeMs, phase));
    const fit = Math.min(size / sw, size / sh);
    const dw = sw * fit;
    const dh = sh * fit;
    ctx.drawImage(img, sx, sy, sw, sh, cx - dw / 2, cy - dh / 2, dw, dh);
  }

  /**
   * Draw fitted into (dx,dy,dw,dh), preserving aspect, centred horizontally and
   * bottom-aligned so feet sit on the floor. `crop="head"` samples the top of
   * the content box (for tiny portrait chips).
   */
  drawFitted(
    ctx: CanvasRenderingContext2D,
    state: SpriteState,
    timeMs: number,
    phase: number,
    dx: number,
    dy: number,
    dw: number,
    dh: number,
    crop: "full" | "head" = "full",
  ): void {
    const slot = this.resolve(state);
    if (!slot) return;
    const { img, meta } = slot;
    const drawState = slot === this.slots[state] ? state : "idle";
    let [sx, sy, srcW, srcH] = this.srcRect(meta, this.frameIndex(meta, drawState, timeMs, phase));
    if (crop === "head") srcH = Math.round(srcH * 0.5);
    const fit = Math.min(dw / srcW, dh / srcH);
    const drawW = srcW * fit;
    const drawH = srcH * fit;
    const drawX = dx + (dw - drawW) / 2;
    const drawY = dy + (dh - drawH);
    ctx.drawImage(img, sx, sy, srcW, srcH, drawX, drawY, drawW, drawH);
  }
}

/** SSR-safe reduced-motion probe, shared by the renderer and home critters. */
export function prefersReducedMotion(): boolean {
  return typeof matchMedia !== "undefined" && matchMedia("(prefers-reduced-motion: reduce)").matches;
}
