/**
 * GENERATED by scripts/build-sprite-manifest.py — do not edit by hand.
 * Uniform-grid geometry + a per-character content trim (union over all
 * states/frames, for stable scale) derived from the sheets in public/sprites.
 */
import type { CharAnims } from "./sprite-atlas";

export const FARMER_SHEETS: Record<string, CharAnims> = {
  jack: {
    idle: { file: "farmers/jack/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 6, y: 0, w: 115, h: 128 } },
    walk: { file: "farmers/jack/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 6, y: 0, w: 115, h: 128 } },
    action: { file: "farmers/jack/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 6, y: 0, w: 115, h: 128 } },
    happy: { file: "farmers/jack/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 6, y: 0, w: 115, h: 128 } },
  },
  molly: {
    idle: { file: "farmers/molly/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 18, y: 0, w: 107, h: 128 } },
    walk: { file: "farmers/molly/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 18, y: 0, w: 107, h: 128 } },
    action: { file: "farmers/molly/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 18, y: 0, w: 107, h: 128 } },
    happy: { file: "farmers/molly/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 18, y: 0, w: 107, h: 128 } },
  },
  rosie: {
    idle: { file: "farmers/rosie/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 0, w: 118, h: 128 } },
    walk: { file: "farmers/rosie/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 0, w: 118, h: 128 } },
    action: { file: "farmers/rosie/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 0, w: 118, h: 128 } },
    happy: { file: "farmers/rosie/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 0, w: 118, h: 128 } },
  },
  billy: {
    idle: { file: "farmers/billy/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 1, w: 109, h: 126 } },
    walk: { file: "farmers/billy/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 1, w: 109, h: 126 } },
    action: { file: "farmers/billy/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 1, w: 109, h: 126 } },
    happy: { file: "farmers/billy/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 10, y: 1, w: 109, h: 126 } },
  },
};

export const ANIMAL_SHEETS: Record<string, CharAnims> = {
  "🐮": {
    idle: { file: "animals/cow/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 6, w: 128, h: 107 } },
    walk: { file: "animals/cow/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 6, w: 128, h: 107 } },
    action: { file: "animals/cow/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 6, w: 128, h: 107 } },
    happy: { file: "animals/cow/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 6, w: 128, h: 107 } },
  },
  "🐓": {
    idle: { file: "animals/chicken/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 14, y: 3, w: 107, h: 121 } },
    walk: { file: "animals/chicken/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 14, y: 3, w: 107, h: 121 } },
    action: { file: "animals/chicken/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 14, y: 3, w: 107, h: 121 } },
    happy: { file: "animals/chicken/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 14, y: 3, w: 107, h: 121 } },
  },
  "🐷": {
    idle: { file: "animals/pig/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 9, w: 127, h: 97 } },
    walk: { file: "animals/pig/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 9, w: 127, h: 97 } },
    action: { file: "animals/pig/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 9, w: 127, h: 97 } },
    happy: { file: "animals/pig/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 0, y: 9, w: 127, h: 97 } },
  },
  "🐑": {
    idle: { file: "animals/sheep/idle.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 1, y: 0, w: 127, h: 116 } },
    walk: { file: "animals/sheep/walk.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 1, y: 0, w: 127, h: 116 } },
    action: { file: "animals/sheep/action.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 1, y: 0, w: 127, h: 116 } },
    happy: { file: "animals/sheep/happy.webp", fw: 128, fh: 128, count: 24, cols: 5, trim: { x: 1, y: 0, w: 127, h: 116 } },
  },
};
