#!/usr/bin/env python3
"""Regenerate src/render/sprite-manifest.ts from the sprite sheets in
public/sprites/. Reads each AutoSprite-exported sheet, derives the uniform-grid
geometry and a per-character content trim (union over all states + frames, so
the figure fills the draw box and never jumps scale between states), and writes
the manifest. Run after downloading fresh sheets:

    python3 scripts/build-sprite-manifest.py

Downloading the sheets themselves is done via the AutoSprite MCP tools (see
docs/sprites.md) — this script only rebuilds the manifest from local files.
"""
from PIL import Image

COLS = 5
STATES = ["idle", "walk", "action", "happy"]
FARMERS = ["jack", "molly", "rosie", "billy", "hazel", "sam", "nell", "gus"]
ANIMALS = ["cow", "chicken", "pig", "sheep"]
EMOJI = {"cow": "🐮", "chicken": "🐓", "pig": "🐷", "sheep": "🐑"}


def sheet_path(group, key, state):
    return f"public/sprites/{group}/{key}/{state}.webp"


def char_meta(group, key):
    """Real frame count = cells up to the last one with content (AutoSprite
    leaves trailing grid cells fully transparent). Trim = union of all content
    boxes across states + frames (cell-local), for stable per-character scale."""
    minx = miny = 10**9
    maxx = maxy = -1
    fw = fh = 256
    counts = {}
    for st in STATES:
        im = Image.open(sheet_path(group, key, st)).convert("RGBA")
        fw = im.width // COLS
        fh = fw
        cells = (im.width // fw) * (im.height // fh)
        # Threshold out faint alpha (downscale bleed between packed cells) so it
        # neither counts as a frame nor inflates the trim box.
        alpha = im.getchannel("A").point(lambda a: 255 if a > 24 else 0)
        last = -1
        for i in range(cells):
            cx = (i % COLS) * fw
            cy = (i // COLS) * fh
            box = alpha.crop((cx, cy, cx + fw, cy + fh)).getbbox()
            if not box:
                continue
            last = i
            x0, y0, x1, y1 = box
            minx = min(minx, x0); miny = min(miny, y0)
            maxx = max(maxx, x1); maxy = max(maxy, y1)
        counts[st] = last + 1 if last >= 0 else cells
    if maxx < 0:
        minx, miny, maxx, maxy = 0, 0, fw, fh
    minx = max(0, minx - 2); miny = max(0, miny - 2)
    maxx = min(fw, maxx + 2); maxy = min(fh, maxy + 2)
    trim = {"x": minx, "y": miny, "w": maxx - minx, "h": maxy - miny}
    return fw, fh, counts, trim


def block(group, key, mapkey):
    fw, fh, counts, t = char_meta(group, key)
    out = [f"  {mapkey}: {{"]
    for st in STATES:
        f = f"{group}/{key}/{st}.webp"
        out.append(
            f'    {st}: {{ file: "{f}", fw: {fw}, fh: {fh}, count: {counts[st]}, '
            f'cols: {COLS}, trim: {{ x: {t["x"]}, y: {t["y"]}, w: {t["w"]}, h: {t["h"]} }} }},'
        )
    out.append("  },")
    return "\n".join(out)


def main():
    ts = [
        "/**",
        " * GENERATED by scripts/build-sprite-manifest.py — do not edit by hand.",
        " * Uniform-grid geometry + a per-character content trim (union over all",
        " * states/frames, for stable scale) derived from the sheets in public/sprites.",
        " */",
        'import type { CharAnims } from "./sprite-atlas";',
        "",
        "export const FARMER_SHEETS: Record<string, CharAnims> = {",
    ]
    ts += [block("farmers", k, k) for k in FARMERS]
    ts += ["};", "", "export const ANIMAL_SHEETS: Record<string, CharAnims> = {"]
    ts += [block("animals", k, f'"{EMOJI[k]}"') for k in ANIMALS]
    ts += ["};", ""]
    with open("src/render/sprite-manifest.ts", "w") as fh:
        fh.write("\n".join(ts))
    print("wrote src/render/sprite-manifest.ts")


if __name__ == "__main__":
    main()
